# Site settings
title: Fallen Heroes Fund &amp; Memorial Tribute

# email: your-email@domain.com

# description:

googleanalytics: UA-63036279-6

# baseurl: "/hfh"
baseurl: "/"

# url: "http://www.hillsboroughsfallenheroes.org" # the base hostname & protocol for your site

# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

# paginate: 10
# paginate_path: "/news/:num"

gems:
 - jekyll-coffeescript
 - jekyll-paginate
