# Site settings

# title: Fallen Heroes Fund &amp; Memorial Tribute

# Build settings
markdown: kramdown

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: 'fallen-hero'
  - scope:
      path: ''
      type: 'pages'
    values:
      layout: 'page'
  - scope:
      path: ''
      type: 'organizations'
    values:
      layout: 'organization'

collections:
  pages:
    output: true
  organizations:
    output: true

# paginate: 10
# paginate_path: "/news/:num"

gems:
  - jekyll-coffeescript
  - jekyll-paginate
