# config.yml

backend:
  name: git-gateway
  branch: master
media_folder: 'assets/uploads'
collections:
  - name: 'heroes'
    label: 'Fallen Hero'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{name}}'
    fields:
      - { name: name, label: 'Name' }
      - {
          name: category,
          label: 'Category',
          widget: 'select',
          options: ['left', 'center', 'right'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      
