# config.yml

backend:
  name: git-gateway
  branch: master
media_folder: 'assets/uploads'
collections:
  - name: 'heroes'
    label: 'Fallen Heroes'
    folder: '_posts/'
    create: true
    fields:
      - { name: Title }
