# config.yml

publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master
media_folder: 'assets/uploads'
collections:
  - name: 'heroes'
    label: 'Fallen Hero'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{name}}'
    fields:
      - { name: name, label: 'Name' }
      - {
          name: dob,
          label: 'Date of Birth',
          widget: 'date',
          required: false,
          formate: 'YYYY-MM-DD',
        }
      - {
          name: date,
          label: 'Date of Death',
          widget: 'date',
          required: true,
          formate: 'YYYY-MM-DD',
        }
      - {
          name: circa,
          label: 'Approximate Dates',
          widget: 'boolean',
          required: false,
          default: false,
          hint: 'Enable this option when exact dates are unknown',
        }
      - {
          label: 'Organization',
          name: 'categories',
          widget: 'relation',
          collection: 'organizations',
          search_fields: ['name', 'permalink'],
          value_field: 'permalink',
          display_fields: ['name'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
      - {
          label: 'Images',
          name: 'images',
          widget: 'list',
          required: false,
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
  - name: 'organizations'
    label: 'Organization'
    folder: '_organizations/'
    create: true
    slug: '{{permalink}}'
    fields:
      - { name: name, label: 'Name' }
      - { name: permalink, label: 'Abbreviation' }
      - { name: ext_link, label: 'External Link', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
